apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "topology-service.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: topology-service
