apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.sealedSecretName }}
spec:
  encryptedData:
    JWT_SECRET: AgPlaceholderReplaceWithSealedValue
    MONGODB_URI: AgPlaceholderReplaceWithSealedValue
    REDIS_URL: AgPlaceholderReplaceWithSealedValue
