apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ripplemark
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/kushal-sharma-works/ripplemark.git
    targetRevision: main
    path: infra/helm/web-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ripplemark
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
