apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-gateway.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-gateway
