apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.sealedSecretName }}
spec:
  encryptedData:
    DATABASE_URL: AgPlaceholderReplaceWithSealedValue
    REDIS_URL: AgPlaceholderReplaceWithSealedValue
    JWT_SECRET: AgPlaceholderReplaceWithSealedValue
    TOPOLOGY_SERVICE_URL: AgPlaceholderReplaceWithSealedValue
    ANALYSIS_SERVICE_URL: AgPlaceholderReplaceWithSealedValue
    REGISTRY_SERVICE_URL: AgPlaceholderReplaceWithSealedValue
